// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-yWpGCTBYy-wLPLlh3xqG4BoyjrVRRMk',
    appId: '1:63175124233:web:790e4b27141043da1d5fd8',
    messagingSenderId: '63175124233',
    projectId: 'goa-dental-solutions-6e0c8',
    authDomain: 'goa-dental-solutions-6e0c8.firebaseapp.com',
    storageBucket: 'goa-dental-solutions-6e0c8.appspot.com',
    measurementId: 'G-14CBL548TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN8_8Rs3DdDwl9mjSd-Y2ZhUVYhaFN3WI',
    appId: '1:63175124233:android:0bd32dbee30036b51d5fd8',
    messagingSenderId: '63175124233',
    projectId: 'goa-dental-solutions-6e0c8',
    storageBucket: 'goa-dental-solutions-6e0c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ3Hwm5c7TWFznJWhlbdk9bCa7MR3yzLs',
    appId: '1:63175124233:ios:cde6db90d26c3bb61d5fd8',
    messagingSenderId: '63175124233',
    projectId: 'goa-dental-solutions-6e0c8',
    storageBucket: 'goa-dental-solutions-6e0c8.appspot.com',
    iosClientId: '63175124233-s577tq06s59rb5iclv5g447sf8biq32s.apps.googleusercontent.com',
    iosBundleId: 'com.example.goaDentalClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ3Hwm5c7TWFznJWhlbdk9bCa7MR3yzLs',
    appId: '1:63175124233:ios:cde6db90d26c3bb61d5fd8',
    messagingSenderId: '63175124233',
    projectId: 'goa-dental-solutions-6e0c8',
    storageBucket: 'goa-dental-solutions-6e0c8.appspot.com',
    iosClientId: '63175124233-s577tq06s59rb5iclv5g447sf8biq32s.apps.googleusercontent.com',
    iosBundleId: 'com.example.goaDentalClinic',
  );
}
